### ISSUE TITLE
url interceptor will not be loaded when use --provider=01-netflix

### ISSUE THREAD

**Issue by omni6** [magiruuvelvet/LightweightQtDRMStreamViewer#2]
As the title say, when starting with --provider, the interceptor script will not be loaded.

**Comment by magiruuvelvet** [comment]
Oh yeah. I figured out what's wrong. Its due to plenty of spaghetti code. I need to refactor this at some point. I fixed it for now.

e7dcb77448f9d56a325e5fe8c94b89111845a319
