### ISSUE TITLE
1080p support on netflix ?

### ISSUE THREAD

**Issue by x0rld** [magiruuvelvet/LightweightQtDRMStreamViewer#25]
does it support 1080p quality on netflix ?
I ask cause chrome does not support it I must add an extension

**Comment by magiruuvelvet** [comment]
No there is no support for this. Netflix is locked to 720p. I don't have any interests in looking into this issue either. I have accepted that Netflix is 720p on Linux.

You can inject user scripts tough using the injection feature (documented in the README under Options) and fiddle around with it yourself. Just note that QtWebEngine is not a browser and can't load fully blown browser extensions, it must be a simple user script.

**Comment by x0rld** [comment]
ok thx
