### ISSUE TITLE
consider to add small config ui in main interface

### ISSUE THREAD

**Issue by omni6** [magiruuvelvet/LightweightQtDRMStreamViewer#4]
like title

would be great to have ability to edit/add provider files from the gui.

**Comment by magiruuvelvet** [comment]
this is actually planned already. i never got around it though. i kinda want to refactor the code first before implementing a graphical configuration manager

**Comment by omni6** [comment]
You know that there are two very similar projects here on github to achieve th same goals? I remember how the fabulous latte-dock was born: psifidotos had the plasmoid (in this days named now-dock) and audoban had the early code for the dock itself (named candil-dock). They merged their stuff and co-worked on latte-dock. @gort818

**Comment by magiruuvelvet** [comment]
a read-only config dialog has been implemented in 8acf08367be78bb81a0d51b520b9b066a4491386

a config writer has been completed in fc33c3f0f8b01c2ab027b573546d103f2d44570b

next step is to add editing functionality to the config dialog. it should be completed very soon

**Comment by magiruuvelvet** [comment]
config dialog is finished
dd62662074314a8e71279c45e10dd6f90de8e000
